<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[TestA...]]>
    </line>
    <line>
      <![CDATA[testA is PASSED]]>
    </line>
    <line>
      <![CDATA[TestB...]]>
    </line>
    <line>
      <![CDATA[testB is FAILED]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="62" started-at="2018-03-15T10:36:54Z" finished-at="2018-03-15T10:36:54Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="62" started-at="2018-03-15T10:36:54Z" finished-at="2018-03-15T10:36:54Z">
      <class name="script.TEST_CLASS">
        <test-method status="PASS" signature="testA()[pri:0, instance:script.TEST_CLASS@5f3a4b84]" name="testA" duration-ms="16" started-at="2018-03-15T10:36:54Z" finished-at="2018-03-15T10:36:54Z">
          <reporter-output>
            <line>
              <![CDATA[TestA...]]>
            </line>
          </reporter-output>
        </test-method> <!-- testA -->
        <test-method status="FAIL" signature="testB()[pri:0, instance:script.TEST_CLASS@5f3a4b84]" name="testB" duration-ms="15" started-at="2018-03-15T10:36:54Z" finished-at="2018-03-15T10:36:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at script.TEST_CLASS.testB(TEST_CLASS.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[TestB...]]>
            </line>
          </reporter-output>
        </test-method> <!-- testB -->
        <test-method status="PASS" signature="end(org.testng.ITestResult)[pri:0, instance:script.TEST_CLASS@5f3a4b84]" name="end" is-config="true" duration-ms="0" started-at="2018-03-15T10:36:54Z" finished-at="2018-03-15T10:36:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testA status=SUCCESS method=TEST_CLASS.testA()[pri:0, instance:script.TEST_CLASS@5f3a4b84] output=TestA...]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[testA is PASSED]]>
            </line>
          </reporter-output>
        </test-method> <!-- end -->
        <test-method status="PASS" signature="end(org.testng.ITestResult)[pri:0, instance:script.TEST_CLASS@5f3a4b84]" name="end" is-config="true" duration-ms="0" started-at="2018-03-15T10:36:54Z" finished-at="2018-03-15T10:36:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testB status=FAILURE method=TEST_CLASS.testB()[pri:0, instance:script.TEST_CLASS@5f3a4b84] output=TestB...]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[testB is FAILED]]>
            </line>
          </reporter-output>
        </test-method> <!-- end -->
      </class> <!-- script.TEST_CLASS -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
